### ISSUE TITLE
API doesn't work

### ISSUE THREAD

**Issue by vrm42** [technobyl/CryptoDredge#30]
tried the new version 10 and the older 9.7 and can't get api to work. I use cuda 10 driver.
command line is -b 0.0.0.0:4068 (tried 127.0.0.1 too)
webpage I try is 192.168.1.155:4068/summary (tried locally too)
result is connection reset in firefox

**Comment by vrm42** [comment]
only the most important detail is missing from your screenshot :(

what is the url in your browser? 127.0.0.1:4031 and 127.0.0.1:4031/summary gives nothing.
something is there because I see the port is open from a different computer (I use 0.0.0.0:4031 actually but 127.0.0.1 also doesn't work locally)

**Comment by melt7777** [comment]
The URL was of our monitoring software called miner.farm. 

The JSON API might be accessible via command on the local machine but not via HTML unless you activate it using some command line options:

--api-type arg     API type {ccminer-tcp (ccminer 2.3 TCP) | ccminer-ws
                         (ccminer 2.3 WebSocket) | off} (default:
                         ccminer-tcp)
  -b, --api-bind arg     IP:port for the miner API, 0 disabled (default:
                         127.0.0.1:4068)

So, by default, you could access the api via the TCP listening port directly using a script such as: 
https://github.com/tpruvot/ccminer/blob/windows/api/summary.pl

Our perl application is able to grasp the data in the same way.

You want to access it via a browser on the same LAN subnet, then perhaps change it to a websocket instead of direct tcp port using:

`--api-type ccminer-ws` 

That should let you access via web.

Hope this helps you!
~ melt
getpimp.org | miner.farm

**Comment by vrm42** [comment]
Hi, I tried every possible combinations months ago. No one in the btctalk forum replied my question. Awesomeminer and ethmonitor can see my rigs fine over API. Now I tried the above perl script and it works too from a different computer. I can cope with it, no need wget anymore. Thank you very much!

**Comment by melt7777** [comment]
Hello - great to hear that you have a working solution. Just wanted to make some friendly helpful suggestions now. 

First, never say "work" and "doesn't work" - explain the expected and actual output and why it is not correct. 
"API doesn't work" 
Better Example: "The API is listening, but I cannot reach it from remote machines via HTTP." 
Reason: If you can access a service from within the box but not outside of it, one would check the firewall next.  Also, you may not be able to access certain miners via curl / browser that way, it may simply be a socket connection.   This may be why the perl script, PiMP OS, and the others are able to access the json api and get the stats, but you cannot access via curl/browser. 

You will see that CryptoDredge is based on the API of ccminer. If only they all used a standard API!

Anyway, hope this answers your question. If so, please close out the issue :)

~ melt
getpimp.org | miner.farm

**Comment by vrm42** [comment]
Hey, your're right - generally speaking. But from a simple user's perspective... I've used basicly all nvidia miners in the last years and their API is simply accessible from any browser so it's easy to assume that CD's API doesn't work. Thanks for your help!
